### ISSUE TITLE
IllegalStateException with zonky.test.database.provider=ZONKY

### ISSUE THREAD

**Issue by rui-zhou-phx** [tomix26/embedded-database-demo#4]
docker is good, 
but this one failed:
zonky.test.database.provider=ZONKY
macos=12.3

<dependency>
	<groupId>io.zonky.test</groupId>
	<artifactId>embedded-database-spring-test</artifactId>
	<version>2.1.1</version>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>io.zonky.test</groupId>
	<artifactId>embedded-postgres</artifactId>
	<version>1.3.1</version>
	<scope>test</scope>
</dependency>

SpringDataJpaAnnotationTest
Caused by: io.zonky.test.db.provider.ProviderException: Unexpected error when preparing a database cluster; nested exception is java.lang.IllegalStateException: Process [/var/folders/tn/16f3f4d11z3bt9831dzwt5nh0000gq/T/embedded-pg/PG-a2a9bc65661eac6f108fc920268a87b3/bin/initdb, -A, trust, -U, postgres, -D, /var/folders/tn/16f3f4d11z3bt9831dzwt5nh0000gq/T/epg5612817711923699469, -E, UTF-8] failed
	at io.zonky.test.db.provider.postgres.ZonkyPostgresDatabaseProvider.createDatabase(ZonkyPostgresDatabaseProvider.java:106)
	at io.zonky.test.db.provider.postgres.ZonkyPostgresDatabaseProvider.createTemplate(ZonkyPostgresDatabaseProvider.java:91)
	at io.zonky.test.db.provider.common.TemplatingDatabaseProvider.createTemplate(TemplatingDatabaseProvider.java:129)
	at io.zonky.test.db.provider.common.TemplatingDatabaseProvider.lambda$createTemplateIfPossible$1(TemplatingDatabaseProvider.java:171)
	at io.zonky.test.db.provider.common.TemplatingDatabaseProvider$TemplateWrapper.loadTemplate(TemplatingDatabaseProvider.java:294)
	at io.zonky.test.db.provider.common.TemplatingDatabaseProvider$TemplateWrapper.access$200(TemplatingDatabaseProvider.java:224)
	at io.zonky.test.db.provider.common.TemplatingDatabaseProvider.createTemplateIfPossible(TemplatingDatabaseProvider.java:171)
	at io.zonky.test.db.provider.common.TemplatingDatabaseProvider.createDatabase(TemplatingDatabaseProvider.java:112)
	at io.zonky.test.db.provider.common.TemplatingDatabaseProvider.createDatabase(TemplatingDatabaseProvider.java:104)
	at io.zonky.test.db.provider.common.PrefetchingDatabaseProvider$PrefetchingTask.lambda$forPreparer$0(PrefetchingDatabaseProvider.java:391)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)

Caused by: java.lang.IllegalStateException: Process [/var/folders/tn/16f3f4d11z3bt9831dzwt5nh0000gq/T/embedded-pg/PG-a2a9bc65661eac6f108fc920268a87b3/bin/initdb, -A, trust, -U, postgres, -D, /var/folders/tn/16f3f4d11z3bt9831dzwt5nh0000gq/T/epg5612817711923699469, -E, UTF-8] failed

tried to clean up the folder but doesn't help

**Comment by dres9** [comment]
I had a similar problem - upgrading to Zonky 2.0.1 fixed it for me.
